# Generated by Django 3.2 on 2021-11-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='engine',
            field=models.FloatField(default=0),
        ),
    ]
